import React from 'react'

export interface TableRow {
  barcode: string // New column for barcode
  group1: string
  group2: string
  group3: string
  productName: string
  turnoverUnits: number
  stockUnits: number
  stockRub: number
  stockDays: number
  turnoverLastOrder: number
}

export const data: TableRow[] = [
  {
    productName: 'Здоровье',
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    turnoverUnits: 39,
    stockUnits: 122,
    stockRub: 4930,
    stockDays: 3.1,
    turnoverLastOrder: 5.5,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Курение',
    turnoverUnits: 941,
    stockUnits: 1791,
    stockRub: 198300,
    stockDays: 1.9,
    turnoverLastOrder: 4.7,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Алкоголь',
    turnoverUnits: 605,
    stockUnits: 2207,
    stockRub: 154069,
    stockDays: 3.6,
    turnoverLastOrder: 5.6,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Бакалейнные товары',
    turnoverUnits: 301,
    stockUnits: 2074,
    stockRub: 74163,
    stockDays: 6.9,
    turnoverLastOrder: 8.5,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Группа не указана',
    turnoverUnits: 1,
    stockUnits: 4,
    stockRub: 46,
    stockDays: 4.0,
    turnoverLastOrder: 7.0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Вода',
    turnoverUnits: 128,
    stockUnits: 552,
    stockRub: 27983,
    stockDays: 4.3,
    turnoverLastOrder: 8.6,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Квас',
    turnoverUnits: 11,
    stockUnits: 52,
    stockRub: 2242,
    stockDays: 4.7,
    turnoverLastOrder: 7.3,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Лимонады и газирование напитки',
    turnoverUnits: 101,
    stockUnits: 756,
    stockRub: 27366,
    stockDays: 7.5,
    turnoverLastOrder: 4.7,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Соки, нектары, морсы',
    turnoverUnits: 25,
    stockUnits: 177,
    stockRub: 6090,
    stockDays: 7.1,
    turnoverLastOrder: 7.9,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Холодный чай: Напиток Липтон Лимоновый чай',
    turnoverUnits: 4,
    stockUnits: 18,
    stockRub: 3153,
    stockDays: 4.6,
    turnoverLastOrder: 4.1,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Холодный чай: Напиток Липтон чай',
    turnoverUnits: 7,
    stockUnits: 33,
    stockRub: 3484,
    stockDays: 4.7,
    turnoverLastOrder: 9.0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Энергетические напитки',
    turnoverUnits: 90,
    stockUnits: 715,
    stockRub: 23755,
    stockDays: 7.9,
    turnoverLastOrder: 7.6,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Все для выпечки',
    turnoverUnits: 4,
    stockUnits: 29,
    stockRub: 354,
    stockDays: 7.2,
    turnoverLastOrder: 4.4,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Готовые блюда',
    turnoverUnits: 235,
    stockUnits: 1372,
    stockRub: 77677,
    stockDays: 5.8,
    turnoverLastOrder: 4.9,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Жевательная резинка',
    turnoverUnits: 20,
    stockUnits: 93,
    stockRub: 3135,
    stockDays: 4.7,
    turnoverLastOrder: 5.8,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Замароженные продукты',
    turnoverUnits: 66,
    stockUnits: 494,
    stockRub: 17308,
    stockDays: 7.5,
    turnoverLastOrder: 7.1,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Карамель, леденцы',
    turnoverUnits: 37,
    stockUnits: 211,
    stockRub: 3952,
    stockDays: 5.7,
    turnoverLastOrder: 7.2,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Молочная гастрономия',
    turnoverUnits: 162,
    stockUnits: 684,
    stockRub: 61488,
    stockDays: 4.2,
    turnoverLastOrder: 7.4,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Мучные кондитерские изделя',
    turnoverUnits: 32,
    stockUnits: 148,
    stockRub: 7164,
    stockDays: 4.6,
    turnoverLastOrder: 8.4,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Мясная гастрономия',
    turnoverUnits: 12,
    stockUnits: 95,
    stockRub: 6065,
    stockDays: 7.9,
    turnoverLastOrder: 4.6,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Рыбная гастрономия',
    turnoverUnits: 5,
    stockUnits: 38,
    stockRub: 1954,
    stockDays: 7.6,
    turnoverLastOrder: 8.7,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Сахар',
    turnoverUnits: 15,
    stockUnits: 92,
    stockRub: 3524,
    stockDays: 6.1,
    turnoverLastOrder: 5.3,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Сахаристые кондитерское изделия',
    turnoverUnits: 7,
    stockUnits: 34,
    stockRub: 658,
    stockDays: 4.9,
    turnoverLastOrder: 8.8,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Фрукты и орехи в глазури, драже',
    turnoverUnits: 13,
    stockUnits: 53,
    stockRub: 2435,
    stockDays: 4.1,
    turnoverLastOrder: 4.6,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Хлеб и выпечка',
    turnoverUnits: 83,
    stockUnits: 427,
    stockRub: 12544,
    stockDays: 5.2,
    turnoverLastOrder: 9.0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'шоколад и шоколадные изделия',
    turnoverUnits: 85,
    stockUnits: 402,
    stockRub: 13652,
    stockDays: 4.7,
    turnoverLastOrder: 8.2,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Яйца',
    turnoverUnits: 10,
    stockUnits: 42,
    stockRub: 6995,
    stockDays: 4.2,
    turnoverLastOrder: 8.7,
  },
]
