export interface TableRow {
  barcode: string // Unique identifier
  group1: string // Main group
  group2: string // Subgroup
  group3: string // Sub-subgroup
  productName: string // Product name
  turnoverUnits: number // Units of turnover
  stockUnits: number // Units in stock
  stockRub: number // Stock value in rubles
  stockDays: number // Stock days
  turnoverLastOrder: number // Turnover since the last order
  turnoverRub: number // Turnover in rubles
  entryPrice: number // Entry price of the product
  sellingPrice: number // Selling price of the product
  turnoverPrice: number // Turnover price
}

// Mock data with populated group and barcode values
export const data: TableRow[] = [
  {
    productName: 'Здоровье',
    group1: 'Продукты',
    group2: 'Напитки',
    group3: 'Чай',
    barcode: '123456789001',
    turnoverUnits: 39,
    turnoverRub: 75000,
    stockUnits: 122,
    stockRub: 4930,
    stockDays: 3.1,
    turnoverLastOrder: 5.5,
    entryPrice: 10,
    sellingPrice: 15,
    turnoverPrice: 58000,
  },
  {
    productName: 'Курение',
    group1: 'Продукты',
    group2: 'Табачные изделия',
    group3: 'Сигареты',
    barcode: '123456789002',
    turnoverUnits: 941,
    turnoverRub: 75000,
    stockUnits: 1791,
    stockRub: 198300,
    stockDays: 1.9,
    turnoverLastOrder: 4.7,
    entryPrice: 50,
    sellingPrice: 70,
    turnoverPrice: 45000,
  },
  {
    productName: 'Алкоголь',
    group1: 'Продукты',
    group2: 'Алкогольные напитки',
    group3: 'Вино',
    barcode: '123456789003',
    turnoverUnits: 605,
    turnoverRub: 75000,
    stockUnits: 2207,
    stockRub: 154069,
    stockDays: 3.6,
    turnoverLastOrder: 5.6,
    entryPrice: 150,
    sellingPrice: 200,
    turnoverPrice: 130000,
  },
  {
    productName: 'Бакалейные товары',
    group1: 'Продукты',
    group2: 'Сыпучие товары',
    group3: 'Мука',
    barcode: '123456789004',
    turnoverUnits: 301,
    turnoverRub: 75000,
    stockUnits: 2074,
    stockRub: 74163,
    stockDays: 6.9,
    turnoverLastOrder: 8.5,
    entryPrice: 20,
    sellingPrice: 30,
    turnoverPrice: 58000,
  },
  {
    productName: 'Группа не указана',
    group1: 'Продукты',
    group2: 'Сырые товары',
    group3: 'Свежие продукты',
    barcode: '123456789005',
    turnoverUnits: 1,
    turnoverRub: 75000,
    stockUnits: 4,
    stockRub: 46,
    stockDays: 4.0,
    turnoverLastOrder: 7.0,
    entryPrice: 5,
    sellingPrice: 8,
    turnoverPrice: 20,
  },
  {
    productName: 'Вода',
    group1: 'Продукты',
    group2: 'Напитки',
    group3: 'Минеральная вода',
    barcode: '123456789006',
    turnoverUnits: 128,
    turnoverRub: 75000,
    stockUnits: 552,
    stockRub: 27983,
    stockDays: 4.3,
    turnoverLastOrder: 8.6,
    entryPrice: 12,
    sellingPrice: 18,
    turnoverPrice: 10230,
  },
  {
    productName: 'Квас',
    group1: 'Продукты',
    group2: 'Напитки',
    group3: 'Безалкогольные напитки',
    barcode: '123456789007',
    turnoverUnits: 11,
    turnoverRub: 75000,
    stockUnits: 52,
    stockRub: 2242,
    stockDays: 4.7,
    turnoverLastOrder: 7.3,
    entryPrice: 8,
    sellingPrice: 10,
    turnoverPrice: 3000,
  },
  {
    productName: 'Лимонады и газированные напитки',
    group1: 'Продукты',
    group2: 'Напитки',
    group3: 'Газировка',
    barcode: '123456789008',
    turnoverUnits: 101,
    turnoverRub: 75000,
    stockUnits: 756,
    stockRub: 27366,
    stockDays: 7.5,
    turnoverLastOrder: 4.7,
    entryPrice: 10,
    sellingPrice: 14,
    turnoverPrice: 16000,
  },
  {
    productName: 'Соки, нектары, морсы',
    group1: 'Продукты',
    group2: 'Напитки',
    group3: 'Соки',
    barcode: '123456789009',
    turnoverUnits: 25,
    turnoverRub: 75000,
    stockUnits: 177,
    stockRub: 6090,
    stockDays: 7.1,
    turnoverLastOrder: 7.9,
    entryPrice: 18,
    sellingPrice: 25,
    turnoverPrice: 4500,
  },
  {
    productName: 'Холодный чай: Липтон Лимонный',
    group1: 'Продукты',
    group2: 'Напитки',
    group3: 'Чай',
    barcode: '123456789010',
    turnoverUnits: 4,
    turnoverRub: 75000,
    stockUnits: 18,
    stockRub: 3153,
    stockDays: 4.6,
    turnoverLastOrder: 4.1,
    entryPrice: 10,
    sellingPrice: 15,
    turnoverPrice: 1500,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Холодный чай: Напиток Липтон чай',
    turnoverRub: 75000,
    turnoverUnits: 7,
    stockUnits: 33,
    stockRub: 3484,
    stockDays: 4.7,
    turnoverLastOrder: 9.0,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Энергетические напитки',
    turnoverRub: 75000,
    turnoverUnits: 90,
    stockUnits: 715,
    stockRub: 23755,
    stockDays: 7.9,
    turnoverLastOrder: 7.6,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Все для выпечки',
    turnoverRub: 75000,
    turnoverUnits: 4,
    stockUnits: 29,
    stockRub: 354,
    stockDays: 7.2,
    turnoverLastOrder: 4.4,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Готовые блюда',
    turnoverRub: 75000,
    turnoverUnits: 235,
    stockUnits: 1372,
    stockRub: 77677,
    stockDays: 5.8,
    turnoverLastOrder: 4.9,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Жевательная резинка',
    turnoverRub: 75000,
    turnoverUnits: 20,
    stockUnits: 93,
    stockRub: 3135,
    stockDays: 4.7,
    turnoverLastOrder: 5.8,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Замароженные продукты',
    turnoverRub: 75000,
    turnoverUnits: 66,
    stockUnits: 494,
    stockRub: 17308,
    stockDays: 7.5,
    turnoverLastOrder: 7.1,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Карамель, леденцы',
    turnoverRub: 75000,
    turnoverUnits: 37,
    stockUnits: 211,
    stockRub: 3952,
    stockDays: 5.7,
    turnoverLastOrder: 7.2,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Молочная гастрономия',
    turnoverRub: 75000,
    turnoverUnits: 162,
    stockUnits: 684,
    stockRub: 61488,
    stockDays: 4.2,
    turnoverLastOrder: 7.4,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Мучные кондитерские изделя',
    turnoverRub: 75000,
    turnoverUnits: 32,
    stockUnits: 148,
    stockRub: 7164,
    stockDays: 4.6,
    turnoverLastOrder: 8.4,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Мясная гастрономия',
    turnoverRub: 75000,
    turnoverUnits: 12,
    stockUnits: 95,
    stockRub: 6065,
    stockDays: 7.9,
    turnoverLastOrder: 4.6,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Рыбная гастрономия',
    turnoverRub: 75000,
    turnoverUnits: 5,
    stockUnits: 38,
    stockRub: 1954,
    stockDays: 7.6,
    turnoverLastOrder: 8.7,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Сахар',
    turnoverRub: 75000,
    turnoverUnits: 15,
    stockUnits: 92,
    stockRub: 3524,
    stockDays: 6.1,
    turnoverLastOrder: 5.3,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Сахаристые кондитерское изделия',
    turnoverRub: 75000,
    turnoverUnits: 7,
    stockUnits: 34,
    stockRub: 658,
    stockDays: 4.9,
    turnoverLastOrder: 8.8,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Фрукты и орехи в глазури, драже',
    turnoverRub: 75000,
    turnoverUnits: 13,
    stockUnits: 53,
    stockRub: 2435,
    stockDays: 4.1,
    turnoverLastOrder: 4.6,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Хлеб и выпечка',
    turnoverRub: 75000,
    turnoverUnits: 83,
    stockUnits: 427,
    stockRub: 12544,
    stockDays: 5.2,
    turnoverLastOrder: 9.0,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'шоколад и шоколадные изделия',
    turnoverRub: 75000,
    turnoverUnits: 85,
    stockUnits: 402,
    stockRub: 13652,
    stockDays: 4.7,
    turnoverLastOrder: 8.2,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
  {
    group1: '',
    barcode: '',
    group2: '',
    group3: '',
    productName: 'Яйца',
    turnoverUnits: 10,
    turnoverRub: 75000,
    stockUnits: 42,
    stockRub: 6995,
    stockDays: 4.2,
    turnoverLastOrder: 8.7,
    entryPrice: 0,
    sellingPrice: 0,
    turnoverPrice: 0,
  },
]
